name: update README
on:
  schedule: [{cron: "*/30 * * * *"}]
  push: {branches: ["master", "main"]}
 
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
     - name: Use Python3
       uses: actions/setup-python@v3
       with:
         python-version: "3.11"
         architecture: "x64"
      
     - name: Update README
       run: |
        pip install "PyGithub" "python-dotenv"
        python3 script.py
       env:
        TOKEN : ${{ secrets.TOKEN }}

      
